import type { Metadata } from "next";
import { Allison, Rajdhani } from "next/font/google";
import "./globals.css";

const rajdhanim = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

const allison = Allison({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-allison",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${rajdhanim.className} ${allison.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
